-- Adds `error_message` to `email_audit_log` — a free-form diagnostic
-- detail captured alongside `error_class` when a send fails. Stores
-- the upstream response body so operators can see the actual rejection
-- reason without scraping server logs:
--
--   * For token-mint failures (HTTP 4xx/5xx from an OAuth token endpoint
--     such as Azure AD), this is the response body (e.g. an `AADSTS70011`
--     scope-validation message).
--   * For SMTP send failures, this is the SMTP enhanced status response
--     (e.g. `535 5.7.3 Authentication unsuccessful [server-id ...]`).
--
-- Sized at VARCHAR(16000) — same precedent as `mazes.definition` — so
-- the column survives the schema rule "every string column is VARCHAR(N),
-- never bare TEXT" (see `0001_initial.sql`). SQLx 0.8's `Any` driver
-- classifies MySQL TEXT as BLOB, which breaks `Option<String>` decoding;
-- VARCHAR is unambiguously Text on every backend. 16000 chars at utf8mb4
-- (~64 KB) matches the historical TEXT cap and is plenty for AAD JSON
-- bodies (~1 KB typical) and verbose provider error pages alike — InnoDB
-- DYNAMIC row format pushes large values off-page so the row-size budget
-- is unaffected. The column is nullable; existing rows stay valid as-is.
--
-- `error_class` remains the stable, low-cardinality dashboard signal
-- (a fixed taxonomy in `service::audit::error_class_for`); the new
-- `error_message` column is the human-readable why and is never aggregated.
ALTER TABLE email_audit_log ADD COLUMN error_message VARCHAR(16000);
