@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Architecture Diagram for Maze Project

Person(user, "User", "A user of the system")
System_Boundary(c1, "Maze Project") {
    Container(console_app, "Maze Console", "Rust", "Console application")
    Container(storage_library, "Storage Library", "Rust", "Maze storage")
    Container(maze_library, "Maze Library", "Rust", "Maze definition and solution calculation")
    Container(utils_library, "Utility Library", "Rust", "Shared utility functions")
}

Rel(user, console_app, "Uses")
Rel(console_app, maze_library, "Uses")
Rel(console_app, storage_library, "Uses")
Rel(console_app, utils_library, "Uses")
Rel(storage_library, utils_library, "Uses")
@enduml