
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Architecture Diagram for Maze

Person(user, "User", "A user of the system")

Container(api, "API", "", ".NET, JavaScript, Rust, Web")
Container(auth, "auth", "Rust", "Authentication library")
Container(browser, "Browser", "", "Internet browser")
Container(html_help, "", "", "HTML help pages")
Container(maze, "maze", "Rust", "Maze library")
Container(maze_c, "maze_c", "Rust", "C API")
Container(maze_console, "maze_console", "Rust", "Console application")
Container(maze_maui_app_net, "Maze.Maui.App", "C#", ".NET maze application (MAUI)")
Container(maze_openapi_generator, "maze_openapi_generator", "Rust", "Console application")
Container(maze_wasm, "maze_wasm", "Rust", "WebAssembly API")
Container(maze_web_server, "maze_web_server", "Rust", "Console application")
Container(storage, "storage", "Rust", "Data storage")

Rel(user, browser, "Uses")
Rel(user, html_help, "Uses")
Rel(user, maze_console, "Uses")
Rel(user, maze_maui_app_net, "Uses")
Rel(user, maze_openapi_generator, "Uses")
Rel(browser, api, "Uses")
Rel(maze_console, api, "Uses")
Rel(maze_maui_app_net, api, "Uses")
Rel(maze_openapi_generator, maze_web_server, "Uses")
Rel(maze_c, maze, "Uses")
Rel(maze_wasm, maze, "Uses")
Rel(api, maze_wasm, "Uses (non-iOS)")
Rel(api, maze_c, "Uses (iOS)")
Rel(api, maze_web_server, "Uses")
Rel(maze_web_server, maze_wasm, "Uses")
Rel(maze_web_server, auth, "Uses")
Rel(maze_web_server, storage, "Uses")

@enduml