@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Architecture Diagram for Maze Project

Person(user, "User", "A user of the system")

System_Boundary(c1, "Browser") {
    Container(browser, "", "", "browser")
}

System_Boundary(c2, "Maze Project") {
    Container(maze_wasm_js, "maze_wasm.js", "Javascipt", "javascript API library")
    Container(maze_wasm, "maze_wasm", "Rust", "web assembly library")
    Container(maze_console, "maze_console", "Rust", "console application")
    Container(storage, "storage", "Rust", "maze storage")
    Container(maze, "maze", "Rust", "maze definition and calculation")
    Container(utils, "utils", "Rust", "utility functions")
}

Rel(user, maze_console, "Uses")
Rel(maze_console, maze, "Uses")
Rel(maze_console, storage, "Uses")
Rel(maze_console, utils, "Uses")
Rel(user, browser, "Uses")
Rel(browser, maze_wasm_js, "Uses")
Rel(maze_wasm_js, maze_wasm, "Uses")
Rel(maze_wasm, maze, "Uses")
Rel(storage, maze, "Uses")
Rel(storage, utils, "Uses")

@enduml