
@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Component Diagram for Maze Project

Person(user, "User", "A user of the system")

System_Boundary(c1, "Browser") {
    Container(browser, "", "", "Internet browser")
}

System_Boundary(c2, "Maze Project") {
    Container(html_help, "", "", "HTML help pages")
    Container(auth, "auth", "Rust", "Authentication library")
    Container(data_model, "data_model", "Rust", "Data model")
    Container(docfx, "docfx", "", "HTML help generation")
    Container(maze, "maze", "Rust", "Maze library")
    Container(maze_maui_app_net, "Maze.Maui.App", "C#", ".NET maze application (MAUI)")
    Container(maze_maui_controls_net, "Maze.Maui.Controls", "C#", ".NET custom controls and definitions (MAUI)")
    Container(maze_maui_services_net, "Maze.Maui.Services", "C#", ".NET custom Services (MAUI)")
    Container(maze_api_net_tests, "Maze.Api.Tests", "C#", "Maze.Api tests")
    Container(maze_api_net, "Maze.Api", "C#", "Maze API .NET assembly")
    Container(maze_wasm_interop_net_tests, "Maze.Wasm.Interop.Tests", "C#", "Maze.Wasm.Interop tests")
    Container(maze_wasm_interop_net, "Maze.Wasm.Interop", "C#", "maze_wasm interop .NET assembly")
    Container(maze_wasm_js, "maze_wasm.js", "Javascipt", "Maze Javascript API library")
    Container(maze_wasm, "maze_wasm", "Rust", "Maze WebAssembly API library")
    Container(maze_c, "maze_c", "Rust", "Maze C API library")
    Container(maze_console, "maze_console", "Rust", "Console application")
    Container(maze_web_api, "", "http", "Maze Web API")
    Container(maze_web_server, "maze_web_server", "Rust", "Console application")
    Container(maze_openapi_generator, "maze_openapi_generator", "Rust", "Console application")
    Container(openapi_json, "openapi.json", "", "JSON file")
    Container(storage, "storage", "Rust", "Data storage")
    Container(utils, "utils", "Rust", "Utility functions")
}

Rel(user, browser, "Uses")
Rel(browser, html_help, "Uses")
Rel(browser, maze_wasm_js, "Uses")
Rel(docfx, html_help, "Produces")
Rel(user, maze_console, "Uses")
Rel(maze_console, data_model, "Uses")
Rel(maze_console, maze, "Uses")
Rel(maze_console, storage, "Uses")
Rel(maze_console, utils, "Uses")
Rel(browser, maze_web_api, "Uses")
Rel(maze_web_api, maze_web_server, "Hosted By")
Rel(maze_web_server, auth, "Uses")
Rel(maze_web_server, data_model, "Uses")
Rel(maze_web_server, maze, "Uses")
Rel(maze_web_server, storage, "Uses")
Rel(user, maze_openapi_generator, "Uses")
Rel(maze_openapi_generator, maze_web_server, "Uses")
Rel(maze_openapi_generator, openapi_json, "Generates")
Rel(openapi_json, html_help, "Used to Generate")
Rel(user, maze_maui_app_net, "Uses")
Rel(maze_maui_app_net, maze_maui_controls_net, "Uses")
Rel(maze_maui_app_net, maze_maui_services_net, "Uses")
Rel(maze_maui_app_net, maze_api_net, "Uses")
Rel(maze_maui_controls_net, maze_maui_services_net, "Uses")
Rel(maze_api_net_tests, maze_api_net, "Uses")
Rel(maze_api_net, maze_wasm_interop_net, "Uses")
Rel(maze_wasm_interop_net_tests, maze_wasm_interop_net, "Uses")
Rel(maze_wasm_interop_net, maze_wasm, "Uses (non-iOS)")
Rel(maze_wasm_interop_net, maze_c, "Uses (iOS)")
Rel(maze_wasm_js, maze_wasm, "Uses")
Rel(maze_wasm, data_model, "Uses")
Rel(maze_wasm, maze, "Uses")
Rel(maze_c, data_model, "Uses")
Rel(maze_c, maze, "Uses")
Rel(storage, data_model, "Uses")
Rel(storage, maze, "Uses")
Rel(storage, utils, "Uses")
Rel(maze, data_model, "Uses")
Rel(maze, utils, "Uses")

@enduml