//! The "internal" [`super::OAuthConnector`] implementation.
//!
//! Speaks OAuth/OIDC directly to each configured provider. Holds one
//! [`ProviderClient`] per enabled provider; per-provider OAuth/OIDC code
//! lives inside each `*ProviderClient` so that adding (say) Microsoft is a
//! matter of dropping in `microsoft.rs` plus a registration line in
//! [`InternalOAuthConnector::from_config`].

mod facebook;
mod github;
mod google;

use crate::config::{ConnectorKind, InternalProviderConfig, OAuthConfig};
use crate::oauth::{
    BeginFlow, FlowOrigin, NormalisedIdentity, OAuthConnector, OAuthError, OAuthProviderPublic,
    PersistedState,
};
use async_trait::async_trait;
use chrono::Utc;
use std::collections::HashMap;

/// Provider-name → backend client. Names are canonical lowercase ("google",
/// "github", ...). The `display_name` in the public-facing list comes from
/// the provider config, not the client.
pub struct InternalOAuthConnector {
    providers: HashMap<String, Box<dyn ProviderClient>>,
    /// Public-facing list, cached at construction so `enabled_providers()` is O(1).
    public: Vec<OAuthProviderPublic>,
}

/// Per-provider seam inside the internal connector. Each provider supplies
/// its own implementation; the dispatcher in [`InternalOAuthConnector`] only
/// needs to know the canonical name.
#[async_trait]
pub trait ProviderClient: Send + Sync {
    /// Construct the authorize URL, given a CSRF-state nonce and a
    /// PKCE-challenge already generated by the connector. Returns the URL
    /// plus the matching PKCE verifier the connector needs to keep.
    async fn begin(&self, state: &str) -> Result<BeginAuthorize, OAuthError>;

    /// Exchange `code` for tokens, fetch userinfo, and return a normalised
    /// identity. `pkce_verifier` is the value produced by `begin()`.
    async fn complete(
        &self,
        code: &str,
        pkce_verifier: &str,
    ) -> Result<NormalisedIdentity, OAuthError>;
}

/// Output of [`ProviderClient::begin`].
pub struct BeginAuthorize {
    pub authorize_url: String,
    pub pkce_verifier: String,
}

impl InternalOAuthConnector {
    /// Build the connector from the resolved [`OAuthConfig`]. `from_config`
    /// expects to be called only when `oauth.connector == Internal` and
    /// `oauth.enabled == true`; otherwise the config-load step would have
    /// errored already.
    pub fn from_config(cfg: &OAuthConfig) -> Result<Self, OAuthError> {
        if cfg.connector != ConnectorKind::Internal {
            return Err(OAuthError::Misconfigured(format!(
                "InternalOAuthConnector built with connector = {:?}",
                cfg.connector
            )));
        }
        let internal = cfg.internal.as_ref().ok_or_else(|| {
            OAuthError::Misconfigured(
                "[oauth.internal] section is missing — should have been caught at config load".into(),
            )
        })?;

        let mut providers: HashMap<String, Box<dyn ProviderClient>> = HashMap::new();
        let mut public: Vec<OAuthProviderPublic> = Vec::new();

        for (name, p) in &internal.providers {
            if !p.enabled {
                continue;
            }
            let canonical = name.to_ascii_lowercase();
            let client: Box<dyn ProviderClient> = build_provider_client(&canonical, p)?;
            providers.insert(canonical.clone(), client);
            public.push(OAuthProviderPublic {
                name: canonical,
                display_name: p.display_name.clone(),
            });
        }

        Ok(Self { providers, public })
    }

    fn provider(&self, name: &str) -> Result<&dyn ProviderClient, OAuthError> {
        let key = name.to_ascii_lowercase();
        self.providers
            .get(&key)
            .map(|b| b.as_ref())
            .ok_or_else(|| OAuthError::UnknownOrDisabledProvider(name.to_string()))
    }
}

/// Map a provider's canonical name to its backend client constructor.
/// Adding a new provider boils down to a new arm here plus a sibling module.
fn build_provider_client(
    canonical: &str,
    cfg: &InternalProviderConfig,
) -> Result<Box<dyn ProviderClient>, OAuthError> {
    match canonical {
        "google" => Ok(Box::new(google::GoogleProviderClient::new(cfg)?)),
        "github" => Ok(Box::new(github::GitHubProviderClient::new(cfg)?)),
        "facebook" => Ok(Box::new(facebook::FacebookProviderClient::new(cfg)?)),
        other => Err(OAuthError::Misconfigured(format!(
            "[oauth.internal.providers.{other}] is enabled but no client implementation exists; \
             supported providers: google, github, facebook"
        ))),
    }
}

#[async_trait]
impl OAuthConnector for InternalOAuthConnector {
    fn enabled_providers(&self) -> Vec<OAuthProviderPublic> { self.public.clone() }

    async fn begin(&self, provider: &str, origin: FlowOrigin) -> Result<BeginFlow, OAuthError> {
        let client = self.provider(provider)?;
        // CSRF nonce must be unguessable; oauth2 crate's CsrfToken does the
        // right thing but we want to keep PKCE / CSRF generation isolated to
        // the provider client so each can use whatever its IdP recommends.
        // The state nonce is generated *inside* the client and surfaced via
        // BeginAuthorize? Actually no — we want the connector to control state
        // because it has to round-trip via the cookie. Generate it here.
        let state = generate_state();
        let begin = client.begin(&state).await?;
        Ok(BeginFlow {
            authorize_url: begin.authorize_url,
            persisted: PersistedState {
                state,
                pkce_verifier: begin.pkce_verifier,
                origin,
                provider: provider.to_ascii_lowercase(),
                created_at_unix: Utc::now().timestamp(),
                client_state: None,
            },
        })
    }

    async fn complete(
        &self,
        provider: &str,
        code: &str,
        cookie_state: &PersistedState,
    ) -> Result<NormalisedIdentity, OAuthError> {
        let client = self.provider(provider)?;
        client.complete(code, &cookie_state.pkce_verifier).await
    }
}

fn generate_state() -> String {
    use base64::Engine;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let mut bytes = [0u8; 32];
    use rand_core::RngCore;
    rand_core::OsRng.fill_bytes(&mut bytes);
    URL_SAFE_NO_PAD.encode(bytes)
}
