@startuml maze_project
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User")
System(system, "Maze System", "A system for managing mazes and calculating their solutions")
Rel(user, system, "Uses")

@enduml