name: build-solver-rust-in-add_dummy_rust_library-branch
run-name: ${{ github.actor }} is running the build workflow for solver-rust within the branch ${{  github.ref }}

on:
  push:
    branches:
      - add_dummy_rust_library
    paths:
      - '**.rs'
      - '**.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Change to project directory
      run: cd $GITHUB_WORKSPACE/src/lib/solvers/solver-rust

    - name: List project directory content
      run: ls -l

    - name: Print project README.md
      run: cat README.md

    - name: Change to src directory
      run: cd src

    - name: List project directory content
      run: ls -l

    - name: Change to lib directory
      run: cd lib

    - name: List project directory content
      run: ls -l

    - name: Change to solvers directory
      run: cd solvers

    - name: List project directory content
      run: ls -l

    - name: Change to solver-rust directory
      run: cd solver-rust

    - name: List project directory content
      run: ls -l

  #  - name: Build
  #    run: cargo build --verbose
      
