name: build-solver-rust-in-add_dummy_rust_library-branch
run-name: ${{ github.actor }} is running the build workflow for solver-rust within the branch ${{  github.ref }}

on:
  push:
    branches:
      - add_dummy_rust_library
    paths:
      - '**.rs'
      - '**.toml'

defaults:
  run:
    working-directory: ./src/lib/solvers/solver-rust

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: List project directory content
      run: ls -l

    - name: Build
      run: cargo build --verbose
      
