name: build-and-test-rust-components-multi-os
run-name: ${{ github.actor }} is running the build and test workflow for Rust components within the branch ${{  github.ref }} on mutliple operating systems

on:
  push:
    branches:

    paths:
      - '**.mjs'
      - '**.rs'
      - '**.toml'

defaults:
  run:
    working-directory: ./src/rust

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Handle Ubuntu-specifics
      if: matrix.os == 'ubuntu-latest'
      run: echo "Running on Ubuntu"
    - name: Handle Mac OS-specifics
      if: matrix.os == 'macos-latest'
      run: echo "Running on Mac OS"
    - name: Handle Windows OS-specifics
      if: matrix.os == 'windows-latest'
      run: echo "Running on Windows OS"

    # Use wasm-pack-action in preference to "cargo install wasm-pack" as ~ 4 minutes faster
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: Build
      run: |
        cargo build --verbose
        cd maze_wasm
        wasm-pack build --target web

    - name: Run Rust Tests
      run: |
        cargo test -p maze
        cargo test -p maze_console -- --test-threads=1
        cargo test -p storage -- --test-threads=1
        cargo test -p maze_wasm
        node --version
        cd maze_wasm/tests
        npm run test_help_examples

    - name: Run API Tests
      run: |
        cd maze_wasm/tests
        npm run test_help_examples

    - name: Benchmark
      run: |
        cargo bench -p maze
