name: build-and-test-rust-components-multi-os
run-name: ${{ github.actor }} is running the build and test workflow for all components within the branch ${{  github.ref }} on multiple operating systems

on:
  push:
    branches:

    paths:
      - '**.cs'
      - '**.csproj'
      - '**.mjs'
      - '**.rs'
      - '**.toml'
      - '**.sln'

defaults:
  run:
    working-directory: ./

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Handle Ubuntu-specifics
      if: matrix.os == 'ubuntu-latest'
      run: echo "Running on Ubuntu"
    - name: Handle Mac OS-specifics
      if: matrix.os == 'macos-latest'
      run: echo "Running on Mac OS"
    - name: Handle Windows OS-specifics
      if: matrix.os == 'windows-latest'
      run: echo "Running on Windows OS"

    - name: Install wasm-pack on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install wasm-pack on Windows
      if: runner.os == 'Windows'
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    
    # Install DocFX in root of the repository
    - name: Install DocFX
      working-directory: ./
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get install -y libunwind8 libicu70 || true
          wget https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip -O docfx.zip
          unzip docfx.zip -d docfx
          chmod +x docfx/docfx.exe
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install mono
          wget https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip -O docfx.zip
          unzip docfx.zip -d docfx
          chmod +x docfx/docfx.exe
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          curl -L https://github.com/dotnet/docfx/releases/download/v2.58.9/docfx.zip -o docfx.zip
          Expand-Archive -Path docfx.zip -DestinationPath docfx
        fi

    - name: Build Rust Components
      working-directory: ./src/rust 
      run: |
        cargo build --verbose
        cd maze_wasm
        wasm-pack build --target web --features "wasm-bindgen"
        cargo build --target wasm32-unknown-unknown --release

    - name: Run Rust Component Tests
      working-directory: ./src/rust 
      run: |
        cargo test -p maze
        cargo test -p maze_console -- --test-threads=1
        cargo test -p storage -- --test-threads=1
        cargo test -p maze_wasm

    - name: Run Rust JavaScript API Tests
      working-directory: ./src/rust 
      run: |
        cd maze_wasm/tests/js
        npm install
        npm run test_api
        npm run test_help_examples

    - name: Run Rust Benchmark Tests
      working-directory: ./src/rust 
      run: |
        cargo bench -p maze

    - name: Setup .NET build environment
      working-directory: ./src/csharp 
      run: |
        dotnet restore
  
    - name: Build .NET components
      working-directory: ./src/csharp 
      run: |
        dotnet build
        
   # - name: Run .NET component tests
   #   working-directory: ./src/csharp 
   #   run: |
   #     dotnet test

    - name: Build .NET Maze.Wasm.Interop documentation
      working-directory: ./src/csharp/Maze.Wasm.Interop
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          ../../../docfx/docfx.exe build
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          ../../../docfx/docfx build
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          ..\..\..\docfx\docfx.exe build
        fi