name: build-and-test-components-multi-os
run-name: ${{ github.actor }} is running the build and test workflow for all components within the branch ${{  github.ref }} on multiple operating systems

on:
  workflow_dispatch:
  push:
    branches:

    paths:
      - '**.cs'
      - '**.csproj'
      - '**.mjs'
      - '**.rs'
      - '**.toml'
      - '**.sln'

defaults:
  run:
    working-directory: ./

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          # - ubuntu-latest
          # - macos-latest
          - windows-latest

    env:
      NET_BUILD_SOLUTION: ${{ matrix.os == 'windows-latest' && 'Build-Windows.sln' || 'Build-Non-Windows.sln' }}
      NET_MOBILE_FRAMEWORK_INCLUSION: ${{ matrix.os == 'windows-latest' && '-p:ExcludeMobileFrameworks=true' || '-p:ExcludeMobileFrameworks=true' }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Handle Ubuntu-specifics
      if: matrix.os == 'ubuntu-latest'
      run: echo "Running on Ubuntu"

    - name: Handle Mac OS-specifics
      if: matrix.os == 'macos-latest'
      run: echo "Running on Mac OS"

    - name: Handle Windows OS-specifics
      if: matrix.os == 'windows-latest'
      run: echo "Running on Windows OS"

    - name: Install wasm-pack on Linux/macOS
      if: runner.os != 'Windows'
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install wasm-pack on Windows
      if: runner.os == 'Windows'
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    
    # - name: Install DocFX
    #   working-directory: ./
    #   run: dotnet tool install -g docfx
  
    # - name: Install Redocly
    #   working-directory: ./
    #   run: npm install -g @redocly/cli

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.404 # Match the version in global.json

    - name: Display active NET SDK version (Windows)
      working-directory: ./src/csharp
      if: runner.os == 'Windows'
      continue-on-error: true
      run: |
        dotnet --version
          
    # - name: Clean Up Existing Workloads (Windows)
    #   if: runner.os == 'Windows'
    #   continue-on-error: true
    #   run: |
    #     dotnet workload uninstall android
    #     dotnet workload uninstall maui-windows
    #     Remove-Item -Recurse -Force "C:\Program Files\dotnet\sdk-manifests\6.0.200" -ErrorAction SilentlyContinue
    #     Remove-Item -Recurse -Force "C:\Program Files\dotnet\sdk-manifests\6.0.300" -ErrorAction SilentlyContinue
    #     dotnet workload repair

    # - name: Restore Workload Manifests (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     dotnet workload update

    # - name: Install Required Workloads (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     dotnet workload install android
    #     dotnet workload install maui-windows

    # - name: Verify Installed SDKs and Workloads (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     dotnet --list-sdks
    #     dotnet workload list

    # - name: Build Rust Components
    #   working-directory: ./src/rust
    #   run: |
    #     cargo build --locked --verbose
    #     cd maze_wasm
    #     wasm-pack build --target web --features "wasm-bindgen"
    #     cargo build --locked --target wasm32-unknown-unknown --release --no-default-features --features "uuid-disable-random"
    #     pwd

    # - name: Set environment variables (non-Windows)
    #   if: runner.os != 'Windows'
    #   working-directory: ./src/rust
    #   run: |
    #     echo "MAZE_WASM_PATH=$(pwd)/target/wasm32-unknown-unknown/release/maze_wasm.wasm" >> $GITHUB_ENV
  
    # - name: Set environment variables (Windows)
    #   working-directory: ./src/rust
    #   if: runner.os == 'Windows'
    #   shell: powershell
    #   run: |
    #     $fullPath = "$($pwd.Path)/target/wasm32-unknown-unknown/release/maze_wasm.wasm"
    #     "MAZE_WASM_PATH=$fullPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # - name: Run Rust Component Tests
    #   working-directory: ./src/rust 
    #   run: |
    #     cargo test --locked -p maze
    #     cargo test --locked -p maze_console -- --test-threads=1
    #     cargo test --locked -p storage -- --test-threads=1
    #     cargo test --locked -p maze_wasm
    #     cargo test --locked -p maze_web_server
    #     cargo test --locked -p maze_openapi_generator

    # - name: Run Rust JavaScript API Tests
    #   working-directory: ./src/rust 
    #   run: |
    #     cd maze_wasm/tests/js
    #     npm install
    #     npm run test_api
    #     npm run test_help_examples

    # - name: Run Rust Benchmark Tests
    #   working-directory: ./src/rust 
    #   run: |
    #     cargo bench -p maze

    # - name: Restore .NET dependencies
    #   working-directory: ./src/csharp 
    #   run: |
    #     dotnet restore ${{ env.NET_BUILD_SOLUTION }} ${{ env.NET_MOBILE_FRAMEWORK_INCLUSION }} 
  
    # - name: Build .NET components
    #   working-directory: ./src/csharp 
    #   run: |
    #     dotnet build ${{ env.NET_BUILD_SOLUTION }} ${{ env.NET_MOBILE_FRAMEWORK_INCLUSION }}

    # - name: Test .NET components
    #   working-directory: ./src/csharp 
    #   run: |
    #     dotnet test ${{ env.NET_BUILD_SOLUTION }} ${{ env.NET_MOBILE_FRAMEWORK_INCLUSION }}

    # - name: Build HTML documentation (Windows)
    #   if: runner.os == 'Windows'
    #   working-directory: ./src/docfx
    #   shell: cmd
    #   run: |
    #     build_all.bat
