name: build-and-deploy-to-github-pages
run-name: ${{ github.actor }} is running the build and deploy to GitHub Pages workflow for the branch ${{  github.ref }}

on:
  workflow_dispatch:
  push:
    branches: main

    paths:
      - '**.cs'
      - '**.csproj'
      - '**.mjs'
      - '**.rs'
      - '**.toml'
      - '**.sln'

permissions:
  pages: write      # Allow writing to GitHub Pages
  contents: write   # Allow modifying repository contents
  id-token: write   # Allow requesting an ID token (needed for deploy-pages action)

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: windows-latest

    env:
      NET_BUILD_SOLUTION: 'Build-Windows.sln'
      NET_MOBILE_FRAMEWORK_INCLUSION: ${{ '-p:ExcludeMobileFrameworks=true' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.404 # Match the version in global.json

    - name: Build Step
      run: echo "Building on ${{ runner.os }}"

    - name: Install wasm-pack on Windows
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'

    - name: Install DocFX
      working-directory: ./
      run: dotnet tool install -g docfx

    - name: Install Redocly
      working-directory: ./
      run: npm install -g @redocly/cli

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.404 # Match the version in global.json

    - name: Clean Up Existing Workloads
      continue-on-error: true
      run: |
        dotnet workload uninstall android
        dotnet workload uninstall maui-windows
        Remove-Item -Recurse -Force "C:\Program Files\dotnet\sdk-manifests\6.0.200" -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "C:\Program Files\dotnet\sdk-manifests\6.0.300" -ErrorAction SilentlyContinue
        dotnet workload repair

    - name: Restore Workload Manifests
      run: |
        dotnet workload update

    - name: Install Required Workloads
      run: |
        dotnet workload install android
        dotnet workload install maui-windows

    - name: Verify Installed Workloads
      run: dotnet workload list
      
    - name: Build Rust Components
      working-directory: ./src/rust
      run: |
        cargo build --verbose
        cd maze_wasm
        wasm-pack build --target web --features "wasm-bindgen"
        cargo build --target wasm32-unknown-unknown --release
        pwd

    - name: Restore .NET dependencies
      working-directory: ./src/csharp 
      run: |
        dotnet restore ${{ env.NET_BUILD_SOLUTION }} ${{ env.NET_MOBILE_FRAMEWORK_INCLUSION }} 
  
    - name: Build .NET components
      working-directory: ./src/csharp 
      run: |
        dotnet build ${{ env.NET_BUILD_SOLUTION }} ${{ env.NET_MOBILE_FRAMEWORK_INCLUSION }}
          
    - name: Build HTML documentation
      working-directory: ./src/docfx
      shell: cmd
      run: |
        build_all.bat
       
    - name: Setup GitHub Pages
      id: pages
      uses: actions/configure-pages@v3
      with:
        enablement: true

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./src/docfx/_site

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
