name: trigger_workflow-on-branch-only-for-rust-file
run-name: ${{ github.actor }} is running the GitHub Actions triggered by changes to a Rust file within the add_dummmy_rust_library branch
on: 
  push:
    branches:
      - add_dummy_rust_library
    paths:
      - '**.rs' # Trigger only if changes are made to .rs files      
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install Bats
        run: npm install -g bats
      - name: Run Bats
        run: bats -v
